### ISSUE TITLE
当开启LuaCoderAssist.metric以后，在一些lua文本内容比较多的页面间来回切换，切换回来后的定位不对

### ISSUE THREAD

**Issue by ltccss** [liwangqian/LuaCoderAssist#10]
如题

**Comment by liwangqian** [comment]
能不能做个小动画演示一下？

**Comment by ltccss** [comment]
好吧，又试了一下，c#也有这个问题，看上去似乎是vscode本身的BUG =。=

**Comment by liwangqian** [comment]
你是不是文件内搜索框处于激活状态？这样来回切换是会有差异。

**Comment by ltccss** [comment]
已经确认是vscode 的设计问题了[#19917](https://github.com/Microsoft/vscode/issues/19917)
看上去似乎怎么解决他们还没有定论╮(╯▽╰)╭
