### ISSUE TITLE
Crashes after VSCode update

### ISSUE THREAD

**Issue by Stanzilla** [liwangqian/LuaCoderAssist#106]
Logs sadly don't have anything useful:

System: macOS 11.2

```
[Info  - 10:21:28 PM] coder inited
[Info  - 10:21:28 PM] extension initialize status: true
[Info  - 10:21:29 PM] Connection to server got closed. Server will restart.
[Info  - 10:21:29 PM] coder inited
[Info  - 10:21:29 PM] extension initialize status: true
[Info  - 10:21:30 PM] Connection to server got closed. Server will restart.
[Info  - 10:21:30 PM] coder inited
[Info  - 10:21:30 PM] extension initialize status: true
[Info  - 10:21:30 PM] Connection to server got closed. Server will restart.
[Info  - 10:21:31 PM] coder inited
[Info  - 10:21:31 PM] extension initialize status: true
[Info  - 10:21:31 PM] Connection to server got closed. Server will restart.
[Info  - 10:21:31 PM] coder inited
[Info  - 10:21:31 PM] extension initialize status: true
[Error - 10:21:32 PM] Connection to server got closed. Server will not be restarted.
```

Looks like this happens when you do not manually set a luacheck path, which is the default. Simply putting `luacheck` in the option fixes it, which means it is properly on the PATH but the extension fails to detect it.

**Comment by liwangqian** [comment]
Yes, the extension dos not use the PATH to search the luacheck executable. The default luacheck packaged with the extension is windows version.

**Comment by Stanzilla** [comment]
> Yes, the extension dos not use the PATH to search the luacheck executable. The default luacheck packaged with the extension is windows version.

I see! Should I make a new ticket for fixing that?

**Comment by liwangqian** [comment]
Yeah, also a PR is welcome :)
