### ISSUE TITLE
请问要如何设置自定义全部变量？

### ISSUE THREAD

**Issue by ltccss** [liwangqian/LuaCoderAssist#11]
我在windows下尝试设置成"LuaCoderAssist.luacheck.configFilePath": "D:/luacheckdefault.luacheckrc"
luacheckdefault.luacheckrc文件里这样子的：
`globals = {"Util",}`
然后看上去它似乎没有工作？

**Comment by liwangqian** [comment]
全局变量可以在ignores配置中增加。
