### ISSUE TITLE
无法显示VSCode的原生触发建议

### ISSUE THREAD

**Issue by hubluesky** [liwangqian/LuaCoderAssist#12]
在没安装（或者禁止）LuaCoderAssist插件运行时，VSCode的书写代码时会有如下提示：
![image](https://user-images.githubusercontent.com/6335104/34933755-0befce12-fa13-11e7-8568-94e87b15e3de.png)
安装（或者开启）LuaCoderAssist插件后，这些没有检查出来的函数将无法显示：
![image](https://user-images.githubusercontent.com/6335104/34933847-6ac529a0-fa13-11e7-89fb-9f8870241f64.png)

**Comment by liwangqian** [comment]
@hubluesky 试下1.3.3.版本吧

**Comment by hubluesky** [comment]
OK，今天试了一下。已经没有问题了，不过我又发现另一个问题。请看#13
