### ISSUE TITLE
使用self加字母时，无法触发VSCode的原生变量建议

### ISSUE THREAD

**Issue by hubluesky** [liwangqian/LuaCoderAssist#13]
1、自定义变量abc
2、使用self.a时无法显示变量建议

原生变量建议图：
![image](https://user-images.githubusercontent.com/6335104/35203948-dbc0bc62-ff65-11e7-8523-65b67511604d.png)

LuaCoderAssist的变量建议图：
![image](https://user-images.githubusercontent.com/6335104/35203989-0f47ad7a-ff66-11e7-8688-3097528ba45e.png)

LuaCoderAssist在使用self加点后会显示本类函数名，这点是值得称赞，我原来一直使用的是VsCodeLua，这个喝好使，但也有许多不合理的地方。希望在self加点后，除了函数名，变量名也能一起显示出来。

**Comment by hubluesky** [comment]
虽然在self.后面会显示函数名，但显示的是require的函数，并没有包括自己本类的函数名。

![image](https://user-images.githubusercontent.com/6335104/35204323-458b9fc0-ff68-11e7-80dc-e1bcf6603f79.png)

**Comment by liwangqian** [comment]
你说的这些问题，当前的实现有点困难，我在重写符号解析的代码，但是最近工作都很忙，可能要到年后才能更新了。

**Comment by liwangqian** [comment]
@hubluesky 简单的修改了下，解决了`self`补全的问题，但是当前是不支持向对象动态增加属性的，也就是说通过`self.abc = 1`这种方式，是无法向`self`对象中增加属性`abc`的，这样一来就无法提供补全了。

修改已经通过1.3.4版本发布，更新试用看看。

**Comment by liwangqian** [comment]
该插件当前对于对象化的编程风格支持的还是比较弱，后续再看是否可以增强。

**Comment by hubluesky** [comment]
已经挺不错的了，再接再厉。
