### ISSUE TITLE
使用方法和问题

### ISSUE THREAD

**Issue by midGitub** [liwangqian/LuaCoderAssist#14]
1.有QQ群之类的不
2.文件之间跳转定义需要定义或者设置哪些东西
3.vscode 自带的 ctrl+t 工作空间内的符号查找无效.
4.luacheck 格式化代码可以用tab代替空格么

**Comment by liwangqian** [comment]
木有QQ群呢😄ctrl+T查找的是所有项目文件的符号，对于大项目来说，性能比较差，所以没有开发这个功能

**Comment by liwangqian** [comment]
文件之间跳转不需要设置就可以用了，如果是项目路径外的文件，需要设置一下再补搜索路径

**Comment by liwangqian** [comment]
代码格式化当前不支持使用tab建
