### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by macjabeth** [liwangqian/LuaCoderAssist#15]
See images below:

![screenshot from 2018-01-28 17-37-36](https://user-images.githubusercontent.com/8473052/35488244-63eb97dc-0453-11e8-8d5d-028d530d60d3.png)
![screenshot from 2018-01-28 17-38-17](https://user-images.githubusercontent.com/8473052/35488246-66532f80-0453-11e8-9d8d-decbd907623b.png)

The first image is displaying the intellisense correctly, but the second image does not show what is inside the `dict` table.

**Comment by liwangqian** [comment]
That's a known problem, currently adding property to table object dynamically is not supported, so may be you can try another way to write the code as show bellow (add support in ver1.3.6):
![image](https://user-images.githubusercontent.com/19996314/35604438-2d253bdc-067d-11e8-8869-d8d8e9397e9f.png)
