### ISSUE TITLE
1.3.4版会自动弹出控制台

### ISSUE THREAD

**Issue by hubluesky** [liwangqian/LuaCoderAssist#16]
在新版本中，使用self.之后，控制台出自动弹出，显示一些错误信息，挺影响体验的。
![image](https://user-images.githubusercontent.com/6335104/35497874-fdaf5a30-0506-11e8-885c-2752c22ed6ad.png)

**Comment by liwangqian** [comment]
bug

**Comment by liwangqian** [comment]
错吧--i写成++i了：）
