### ISSUE TITLE
LuaCoderAssist.luacheck.enable does not affect whether or not luacheck is enabled

### ISSUE THREAD

**Issue by marth8880** [liwangqian/LuaCoderAssist#17]
The setting `LuaCoderAssist.luacheck.enable` does not affect whether or not luacheck is enabled, and I would _very_ much love to disable it.

Currently the only way to disable it is by renaming/removing the luacheck exe that comes with the extension.

**Comment by liwangqian** [comment]
@marth8880 yeah, thanks for your issue, this problem is fix in ver1.3.7, try again please.

**Comment by marth8880** [comment]
Verified fixed. Thanks so much!
