### ISSUE TITLE
How to LDoc 

### ISSUE THREAD

**Issue by SWSAmor** [liwangqian/LuaCoderAssist#18]
Insert LDoc isn't working for me. What do i wrong?

Otherwise best extension what i used. Thank you very much!

**Comment by liwangqian** [comment]
could you provide more detsils ？

**Comment by SWSAmor** [comment]
My cursor at a function header line, i press right click, select "Insert LDoc" menu entry and nothing happens.

**Comment by SWSAmor** [comment]
It seems LuaCoderAssist know
`local something = function()`
fomat, but doesn't recognize 
`local module.something = function()`
format.

Could you fix that?

**Comment by liwangqian** [comment]
@SWSAmor The expression `local module.something = xxx` is valid syntax ?

**Comment by SWSAmor** [comment]
Sry without local, here is an example from a working app:
>local user =  {}
>...
>user.registration = function(self, tparam) ... end
>user.settings = function(self, tparam) ... end
>...
>return user

**Comment by liwangqian** [comment]
@SWSAmor This problem is solved by https://github.com/liwangqian/LuaCoderAssist/commit/0e4d2f7411391f10da3c866e3715f6cb3fa5c928

Try the latest version.

**Comment by SWSAmor** [comment]
It's working great. Thank you.
