### ISSUE TITLE
Add a way to extend autocomplete

### ISSUE THREAD

**Issue by Positive07** [liwangqian/LuaCoderAssist#22]
I come from Atom and over there we use a package called [autocomplete-lua-plus](https://github.com/dapetcu21/atom-autocomplete-lua)

This package can then be extended by other plugins in order to provide autocomplete for other modules, using a format called `.luacompleterc` which is a JSON schema described in the README of the aforementioned plugin.

This kind of extensibility would be great for stuff like frameworks and libraries and would allow an easy way to provide advanced autocomplete for this kind of modules.

**Comment by Positive07** [comment]
The autocomplete packages uses luaparse too ([a modified version](https://github.com/dapetcu21/luaparse)) and the code for loading the `.luacompleterc` can be found [here](https://github.com/dapetcu21/atom-autocomplete-lua/blob/master/lib/options/luacompleterc.js) which is then used when doing the [static analysis](https://github.com/dapetcu21/atom-autocomplete-lua/blob/master/lib/analysis.js)

This format is great cause there are already files for [standard Lua and LuaJIT](https://github.com/dapetcu21/atom-autocomplete-lua/tree/master/lib/stdlib) versions and frameworks like [LÖVE](https://github.com/rm-code/love-atom) and [Defold](http://atom.io/packages/defold-ide)

This format has been implemented in Lua too, in a similar project called [lua-lsp](https://github.com/Alloyed/lua-lsp#configuration) which is an attempt at a complete Language Server Protocol for the Lua language made in Lua itself.

**Comment by liwangqian** [comment]
@Positive07 That's a good suggestion, This is an efficient way to provide better completion, may be we can implement this feature together ：)

**Comment by Positive07** [comment]
I would love to, I'm getting familiar with both codebases since it was a long time ago that I had the chance to contribute to autocomplete-lua.

If you have any pointers please tell me, is the main analysis happening in, [symbol-parser](https://github.com/liwangqian/LuaCoderAssist/blob/master/server/providers/lib/symbol-parser.js) and [symbol-manager](https://github.com/liwangqian/LuaCoderAssist/blob/master/server/providers/lib/symbol-manager.js)? If so, you are not using the [event handlers provided by luaparse](https://oxyc.github.io/luaparse/luaparse.html#section-186) like `onCreateNode`, `onCreateScope` and such right?

**Comment by liwangqian** [comment]
@Positive07 Yes, I'm not using the event handlers provided by luaparse, the main analysis is `symbol-parser` and the files under dir `server\lib\symbol\types`.

Currently the symbols are stored in an index array without structure, that's the main difference from autocomplete-lua, maybe that's the time to make the change to use the structure way.

**Comment by Positive07** [comment]
Yes I think that's where we should start, this type of structure should simplify stuff a lot for detecting types.

Then it's just a matter of adding the type definitions to the global scope, that part should be fairly easy.

Maybe we can start a new branch for this since it's a big rework on this side? Or how do you prefer to work on this?

PS: If you have Discord (I'm Positive#8080 over there) or any other messaging client we can use to chat faster we could discuss it better haha I live in Argentina so there is probably a big time zone difference but I stay late most of the days so it should be doable

**Comment by liwangqian** [comment]
I prefer a new branch, I have to work in workdays, so i'm free on weekends ： )

I have to say that, I test autocomplete-lua in my real-works, it's not fast-respond when i edit a large file( 5000+line)，and we should consider this on the development of this new feature.

**Comment by Positive07** [comment]
autocomplete-lua parses with luaparse every time you type until your cursor and then tries to continue using a weird method so that luaparse doesn't error

It does this to determine the actual scope and variable you are indexing, and if you are actually writing a variable name or a keyword and such

Not sure how much needed that is, or if it can be solved in a different way, it probably can

**Comment by liwangqian** [comment]
I think it's type deduce system is very good but time expensive, maybe we can let user choose whether to use the new engine with type deduce.

**Comment by Positive07** [comment]
That would be a sane option yeah, though it will be harder to maintain.

Is it possible to benchmark this kind of things? It would probably be better if we compare with real numbers and see which parts are the most expensive and try to reduce those later on. Right now I really don't see what parts have the most impact on performance so it's really hard to tell

**Comment by liwangqian** [comment]
@Positive07 I think we can implement the loader for the `.luacompleterc` currently, this is more easy to achieve, and then we add the `symbols` loaded from `.luacompleterc` to the complete list. This is loaded once and will not affect the `symbol-parser`. How do you think of it?

**Comment by liwangqian** [comment]
not yet

**Comment by Positive07** [comment]
I saw you have been working on it, I need to investigate more on what you have done

**Comment by liwangqian** [comment]
I workout a maybe more effective way to implement this feature, that's the `lazy evaluation` tech, this can help reduce the unnecessary search work when parsing the ast nodes, the type info is deduced only when we really need it.

**Comment by liwangqian** [comment]
the current work is a little massive, may be you can help me to reconstruct it.

**Comment by liwangqian** [comment]
and, it's type merge is to complicated, maybe we can simplify it.

**Comment by liwangqian** [comment]
you know i mean the autocomplete-lua ;)

**Comment by AdamFrisby** [comment]
Any tips or pointers where you need the help to get this in?

**Comment by liwangqian** [comment]
@Positive07 @AdamFrisby I have implement `definitionProvider` and `completionProvider` in the new engine, and it's buggy, could you help me to review the code ?
https://github.com/liwangqian/LuaCoderAssist/tree/br_NewEngine

**Comment by AdamFrisby** [comment]
Excellent, any pointers to getting started with it? if so I can give it a test run through and see if I can't help solve some of those bugs.

**Comment by liwangqian** [comment]
@AdamFrisby Yes, you can start from the simple test example:
https://github.com/liwangqian/LuaCoderAssist/blob/br_NewEngine/test/test.engine.js

The engine code is in https://github.com/liwangqian/LuaCoderAssist/tree/br_NewEngine/server/lib/engine

**Comment by liwangqian** [comment]
It works now in vscode completion, something like this:
![test](https://user-images.githubusercontent.com/19996314/41047720-c38219e0-69df-11e8-8896-804b43ff84f9.gif)

**Comment by liwangqian** [comment]
@Positive07 @AdamFrisby @FireSiku Hi, the new version is going to release, and some of the most interest features has implement, maybe you can have a try and give some feedback.

https://github.com/liwangqian/LuaCoderAssist/releases/tag/v2.0.1-release

**Comment by AdamFrisby** [comment]
Fantastic, will do.

Does the .luacompleterc pickup the same way as in Atom? (will search same dir & parent directories to root)

**Comment by liwangqian** [comment]
@AdamFrisby Sorry to say that, I adopt another way for extending 3rd libraries, by providing a lua file which defines the interfaces of the 3rd library, see for example: https://github.com/liwangqian/LuaCoderAssist/blob/br_NewEngine/stdlibs/lua_5_1.lua

This takes the advanture of the symbol parse engine, and more flexible.

**Comment by AdamFrisby** [comment]
Ah I see - the reason why we wanted the luacompleterc support was we interface into non-lua components, so building the bindings in lua is tricky (doing the conversion to the json representation was by contrast a lot simpler).

Could we put a bounty for .luacompleterc support up? If you're interested - let me know how much it would cost and email it to me - adam@sinewavecompany.com

**Comment by Positive07** [comment]
Yeah I agree, representing something like the LÖVE API in that format would be too tricky, it has a lot of argument variants (optional arguments) and different Object types... plus it's spread into a bunch of modules like `love.graphics`, `love.windows` and such

**Comment by liwangqian** [comment]
@Positive07 May you some example .luacompleterc file, and i will try my best to implement it.

**Comment by liwangqian** [comment]
@Positive07 @AdamFrisby @FireSiku The new version which support the .luacompleterc file to provide completion had release, try it please and make some feedback.

https://github.com/liwangqian/LuaCoderAssist/releases/tag/v2.0.3-release

**Comment by AdamFrisby** [comment]
Fantastic - will give it a try, thankyou!

**Comment by AdamFrisby** [comment]
Having some issues still - the file is not being picked up or loaded correctly (stored in the same folder as the Lua file), have attached. Should autocomplete from Space.* (which is a global table declared in the rc)

[Lua Tests.zip](https://github.com/liwangqian/LuaCoderAssist/files/2365277/Lua.Tests.zip)

**Comment by AdamFrisby** [comment]
Nevermind - it works; the file has to be in the same directory as the Workspace root. 👍 

Thankyou!

**Comment by Positive07** [comment]
@liwangqian I tested the pre-release and it's great! it works really well for modules and the argument completion works flawlessly

My further questions would be:

* Could it support [Type definitions](https://github.com/dapetcu21/atom-autocomplete-lua#type-definitions) and [Named types](https://github.com/dapetcu21/atom-autocomplete-lua#named-types) from the original `.luacompleterc` format?
* Could we have a directory where we can put a bunch of `.luacompleterc` files and then somehow "require" them into our project? Having LÖVE's `.luacompleterc` file in each project is kind of a pain

If you want I can split this issue into two (or one) new issues... or I could just reopen and rename this issue to further discuss support of the `.luacompleterc` file

**Comment by AdamFrisby** [comment]
I believe named types work - we've been using them extensively.

**Comment by Positive07** [comment]
Mmm I can't seem to get autocomplete for methods on the named types, for example if `love.audio.newSource` returns a `source` object with a `sound:setPitch` method the `setPitch` part doesn't get autocompleted

**Comment by Positive07** [comment]
Wanted to chime in and say that the new update is amazing! Just waiting for 6c43443 to land thanks a lot @liwangqian

**Comment by liwangqian** [comment]
@Positive07 If the LOVE completion file built-in is not updated, there are two ways to solve this problem currently:
1) Any one submit an PR to update;
2) Use the `.luacompleterc` and disable the `useLove` config.
