### ISSUE TITLE
General autocomplete improvements

### ISSUE THREAD

**Issue by Positive07** [liwangqian/LuaCoderAssist#23]
Busted autocomplete is sometimes intrusive when doing non busted related work, so maybe that could be enabled/disabled per project?

Also adding standard library autocomplete would be amazing, maybe related to #22 and if so then busted could fall into that too. Note that LuaJIT adds its own globals like `bit`, `jit` and `ffi` which could be considered part of the standard library for LuaJIT

I don't think there is any keyword autocomplete? That would be great too. In a `for` loop it should suggest `in`, `do` and `end`, but also `if`, `while`, `repeat`, `for` and `function` too (of course depending on what you type). Currently no keyword is suggested unless they are already in the file

**Comment by liwangqian** [comment]
the busted completion is provided through the snippet, and it's enabled automatic, it seems there is no way to disabled this.

**Comment by Nexela** [comment]
As a request,   Possibly drop the button (or make a setting to hide it) and just auto switch to busted mode when a busted file is open using the same format as luacheck  *_spec.lua  Additionaly these files auto-append the busted std in the latest luacheck.

> Added default stds equivalent to predefined per-path std overrides in config:
    files["**/spec/**/*_spec.lua"].std = "+busted";
    files["**/test/**/*_spec.lua"].std = "+busted";
    files["**/tests/**/*_spec.lua"].std = "+busted";

**Comment by liwangqian** [comment]
We cannot assume the file contains `_spec` must be a lua unit test file for busted.

**Comment by Positive07** [comment]
I would consider that now that `.luacompleterc` are a thing we could just use one for busted when needed...

As I said in [this comment](https://github.com/liwangqian/LuaCoderAssist/issues/22#issuecomment-424907022)
>Could we have a directory where we can put a bunch of .luacompleterc files and then somehow "require" them into our project?

This could mean there would be a `busted.luacompleterc` which you could include for the specified files. It would be a really good way to solve this issue

**Comment by liwangqian** [comment]
Em, the `Busted` button is defined for dynamic enable/disable the code complete of busted interfaces.

When you editing a non busted test file, and if you don't like the busted interfaces to be complete, you can disable it.

Configuration like `Use Love` is not so convenient.
