### ISSUE TITLE
Build/test system

### ISSUE THREAD

**Issue by mika76** [liwangqian/LuaCoderAssist#24]
I tried to get a dev build going but it seems that you are using an "old" way of running a test system instead of the way Microsoft has defined it by running the client from the debug menu and attaching to the language server.

I think you should update the project to the latest way since it's much easier...

**Comment by liwangqian** [comment]
Yes, a PR is welcome :)

**Comment by mika76** [comment]
Are you interested in converting the project to typescript?

**Comment by liwangqian** [comment]
not currently😁
