### ISSUE TITLE
Lint/diagnostics bug

### ISSUE THREAD

**Issue by go3k** [liwangqian/LuaCoderAssist#25]
语法错误检查有问题，写一个语法错误的语句，错误提示出现大约3秒钟后自动消失。

**Comment by liwangqian** [comment]
有例子代码吗？

**Comment by go3k** [comment]
我这里是必现的，例如：
function a()
sss    --- 关于这一行的错误提示只有3s左右
end

**Comment by liwangqian** [comment]
3s是代码里的延时，最新的版本减少了延时，实际luacheck会提示end这一行错误，具体如下：
![image](https://user-images.githubusercontent.com/19996314/46448050-ab332b00-c7b7-11e8-894e-26bf7aecbd42.png)

**Comment by liwangqian** [comment]
实现最新的版本
