### ISSUE TITLE
Support for LSP stdio server

### ISSUE THREAD

**Issue by Kaali** [liwangqian/LuaCoderAssist#26]
I made a quick hack to get LuaCoderAssist working in Emacs for me. By implementing a stdio version of the LSP protocol.

https://github.com/Kaali/LuaCoderAssist/commit/75effefcacfef975b7d6763e9f9c086fab2e4328

I haven't tested it with VSCode, but if you want to pull it in, it's there for the taking.

**Comment by liwangqian** [comment]
Yes, I will accept your PR if it runs OK in VSCode.
