### ISSUE TITLE
Adding functions inherited through setmetatable to autocompletion

### ISSUE THREAD

**Issue by gkocik** [liwangqian/LuaCoderAssist#29]
Hi,
do you think that it is possible to add support to autocompletion of functions that are inherited using metatable? Example in gif below:

![lua](https://user-images.githubusercontent.com/1702858/44430357-b41ac500-a59a-11e8-98ba-002c6a7ab281.gif)

As you can see table B should inherit function Foo from table A (and it worked in runtime - look at the debug console, there is "foo" printed out) but vscode did not suggested this in autocompletion (it did but only because this keyword was already used in same document, it was not suggested as member function of table B). Also if table A would be in different file and got required using local A = require("a") go to definition would not work as well.

**Comment by liwangqian** [comment]
Yes, this feature is under development and needs some time to come out.

**Comment by liwangqian** [comment]
@gkocik The feature has come out, try it and make some feedback.

https://github.com/liwangqian/LuaCoderAssist/releases/tag/v2.0.1-release

**Comment by gkocik** [comment]
Did a quick check - works fine if both tables are in same file. Only thing I noticed is that when you press ctrl + space to show suggestions again than this list does not contain inherited fields. But beside that looks great - thank you!

Unfortunately it does not work if parent table resides in different file and it gets included using
local Foo = require ("foo")

if another table will set foo as it's metastable than editor will not suggest inherited fields because foo resides in other file. Is this something that you can add?

**Comment by liwangqian** [comment]
@gkocik Yes, the require expression is not evaluated, this is fixed in [VER-2.0.2](https://github.com/liwangqian/LuaCoderAssist/releases/tag/v2.0.2-release), try it. 

I have to point out that, The first time you type `A.`, it may not give complete suggestion, and you should try to type second time. This is because the `lazy evaluation` algo, when `local A = require("a")`, the type of symbol `A` is not deduced for performance consideration, but only when the symbol really needs to know it's type.

**Comment by liwangqian** [comment]
The `Lazy Evaluation` is important when we edit a large lua file(2000+ lines) with a lot of symbols.

**Comment by gkocik** [comment]
Hi, sorry for not responding in time. I checked it few days ago - mostly it works fine on simple examples but when i tried to use this functionality on my main project which is much more complicated it did not worked as expected. I wasn't able to find out what was the cause.Unfortunately for some time i wont be able to check it again due to lack of free time, but i'll try to get back into it next weekend and search for solid repro steps.
