### ISSUE TITLE
Type & Hover Error

### ISSUE THREAD

**Issue by macjabeth** [liwangqian/LuaCoderAssist#3]
Opening a large lua file gave me this error:
```
[Info  - 7:33:33 PM] extension initialize status: false
[Error - 7:33:33 PM] Notification handler 'workspace/didChangeConfiguration' failed with message: path must be a string or Buffer
TypeError: Cannot read property 'parse' of undefined
    at SymbolManager.parseDocument (/home/boonie/.vscode-insiders/extensions/liwangqian.luacoderassist-1.2.3/server/providers/lib/symbol-manager.js:30:27)
    at Coder.onDidChangeContent (/home/boonie/.vscode-insiders/extensions/liwangqian.luacoderassist-1.2.3/server/coder.js:88:37)
    at documents.onDidChangeContent (/home/boonie/.vscode-insiders/extensions/liwangqian.luacoderassist-1.2.3/server/server.js:50:11)
    at CallbackList.invoke (/home/boonie/.vscode-insiders/extensions/liwangqian.luacoderassist-1.2.3/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/home/boonie/.vscode-insiders/extensions/liwangqian.luacoderassist-1.2.3/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at connection.onDidOpenTextDocument (/home/boonie/.vscode-insiders/extensions/liwangqian.luacoderassist-1.2.3/node_modules/vscode-languageserver/lib/main.js:174:38)
    at handleNotification (/home/boonie/.vscode-insiders/extensions/liwangqian.luacoderassist-1.2.3/node_modules/vscode-jsonrpc/lib/main.js:476:43)
    at processMessageQueue (/home/boonie/.vscode-insiders/extensions/liwangqian.luacoderassist-1.2.3/node_modules/vscode-jsonrpc/lib/main.js:248:17)
    at Immediate.<anonymous> (/home/boonie/.vscode-insiders/extensions/liwangqian.luacoderassist-1.2.3/node_modules/vscode-jsonrpc/lib/main.js:235:13)
    at runCallback (timers.js:672:20)
```

And when I hover over any of the variables in the file, I'm getting this error:
```
[Error - 7:34:14 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'provideHover' of undefined
  Code: -32603 
[Error - 7:34:34 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'provideHover' of undefined
  Code: -32603 
```

Happy to provide any other information necessary to sort out this issue.

**Comment by liwangqian** [comment]
@macjabeth Did you open the file directly instead of open the folder containing the file ? In this case, the extension cannot initialized correctly, as your log shows: 
`[Info  - 7:33:33 PM] extension initialize status: false`

I known this problem, but i did not fix it, a little lazzy :)

**Comment by liwangqian** [comment]
@macjabeth try Ver 1.2.5 please.

**Comment by macjabeth** [comment]
@liwangqian Yes, I opened it directly instead of opening the folder containing the file. Sorry for the late reply, I fell asleep :)

And ok, I'm waiting for the update to come through in VSCode. Will let you know how it goes!

**Comment by macjabeth** [comment]
@liwangqian I'm not getting the first error message anymore, but it seems like the ones showing up in the second image I posted still are.

This is after hovering over any of the variables there:
![image](https://user-images.githubusercontent.com/8473052/32700446-dc52ceea-c7c5-11e7-862e-6c623053355a.png)

Also, the intellisense wasn't working on this file for some reason. Maybe because it was too large? I'm not sure - any insight would be appreciated!
![image](https://user-images.githubusercontent.com/8473052/32700459-1a9b8c82-c7c6-11e7-8374-6849eff34b58.png)

**Comment by liwangqian** [comment]
@macjabeth From the description you give, I guess there is something failed while parsing the file, so document symbols did not generate, and so hover/intellisense did not work.

I need more information to figure out the problem.  I guess is there any syntax error in your file? This can be check from the **PROBLEMS** panel.

**Comment by macjabeth** [comment]
@liwangqian One problem does show up:

![image](https://user-images.githubusercontent.com/8473052/32729114-fd66bef8-c882-11e7-9d6b-02a8292e5c1b.png)

When I change the file size limit in the settings, the error goes away and a new one presents itself in the **OUTPUT** panel:

```
[Info  - 2:59:25 PM] coder inited
[Info  - 2:59:25 PM] extension initialize status: true
(node:27103) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'split' of undefined
(node:27103) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 2:59:28 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'concat' of undefined
  Code: -32603 
```

However, when I look at the PROBLEMS panel, it says no problems have been detected.

That being said, I decided to do a little debugging and try and pinpoint the error in the script. It turns out that the error is only showing up when I take the `.lua` extension off the file name and manually set the language of the file to lua.

For example:
`filename` - manually set file language to lua: error shows up when hovering over any variables
`filename.lua` - error does not show up and hovering works as expected

**Comment by liwangqian** [comment]
@macjabeth Thanks for your help to figure out this problem, I will fix it next day, have to go sleep.

**Comment by liwangqian** [comment]
@macjabeth try ver 1.2.7 please, review at  https://github.com/liwangqian/LuaCoderAssist/commit/a74f19226fcc76f0088556d1c776be73ef3d9620
