### ISSUE TITLE
luacheck settings should default to unset.

### ISSUE THREAD

**Issue by Nexela** [liwangqian/LuaCoderAssist#30]
The default CLI arguments should contain no extra paramaters and instead be wrapped in settings checks.
This will allow for 'out of the box' working with .luacheckrc (this file by default is looked for in the cwd up to drive root, in the users home directory, and finally in the luacheck appdata directory on windows)

`const defaultOpt = ['--no-color', '--codes', '--ranges', '--formatter', 'plain'];`

`'-m'`  and `'-t''` should be removed or have their own settings.entry

```
        if (docSym) {
            globals = docSym.dependences().map((dep) => {
                return dep.name;
            });
        }

        if (globals.length > 0) {
            args.push('--read-globals');
            args.push.apply(args, globals);
}
```
Should also be wrapped in a settings check.

Also a minor thing but finally
if a .luacheckrc has an error in it, outputting the error could be helpful. Example output string follows
`Critical error: Couldn't load configuration from ..\.luacheckrc: syntax error (line 163: '}' expected (to close '{' at line 156) near 'util')`

**Comment by liwangqian** [comment]
I use the `-m -t` argument because my work is still using the lua 5.1 module style, this can be solved by detecting the style of the lua module.

**Comment by Nexela** [comment]
One option is to have a settings.cliArguments string type that will get pre-pending when building the args list
settings.cliArguments ["-m", "-t"]
