### ISSUE TITLE
关于全局变量的支持

### ISSUE THREAD

**Issue by midGitub** [liwangqian/LuaCoderAssist#33]
![image](https://user-images.githubusercontent.com/20261416/45813654-c2790f80-bd05-11e8-84e6-86a3812f548f.png)
![image](https://user-images.githubusercontent.com/20261416/45813665-c7d65a00-bd05-11e8-9aab-32d1d3a4b596.png)
![image](https://user-images.githubusercontent.com/20261416/45813685-d886d000-bd05-11e8-806e-9d93407ad7da.png)
1. 请问目前支持全局变量的定义的跳转不.
2. 面向对象式的定义跳转
3. 建议增加 格式化代码的时候 是否可以设置 不去掉table的最后一个元素的逗号，不去掉的话也是符合lua语法的。这样子，在追加table成员的时候不用再手动敲 , 进去..

**Comment by midGitub** [comment]
图1 是，我选择语法为lua 5.3 的时候 ，使用table.unpack 会提醒没这个方法。应该得有才对

**Comment by liwangqian** [comment]
1. 插件是支持全局变量跳转的，你那里是遇到了什么问题，具体可以举例子说下；
2. 最新版本(V2.0.8)已经支持有限的面向对象式的定义跳转和补全了，你可以更新试用下；
3. 代码格式化的，当前是基于lua-fmt这个库来做的，暂时还没办法按你的要求来定制，后续有时间的话可以考虑。

table.unpack这个luacheck告警感觉不应该是这样，具体要看下啥原因。

**Comment by liwangqian** [comment]
@midGitub table.unpack这个告警的问题，应该是因为你在修改luaversion为5.3的时候，没有同时将luacheck.std这个配置也改下，所以报了这个unpack函数不存在。这个后续改成根据luaversion来自动匹配luacheck的参数，这样就不用改两个配置了。
