### ISSUE TITLE
Most recent linting error/warning doesn't go away even when corrected

### ISSUE THREAD

**Issue by Nexela** [liwangqian/LuaCoderAssist#37]
![image](https://user-images.githubusercontent.com/13972192/46453139-dabd4580-c76d-11e8-9ed9-033b9868a5c1.png)

**Comment by Nexela** [comment]
Neither file has an error currently.  Closing the file and reopening it
shows 0 problems correctly.  It is just the last warning displayed doesn't
go away when fixed

**Comment by Nexela** [comment]
![image](https://user-images.githubusercontent.com/13972192/46576013-788f5b00-c98e-11e8-899e-2cfdef787669.png)

**Comment by Nexela** [comment]
Still happens in 2.1.1

Re the earlier comment, neither file has any errors/warnings the message just doesn't go away when they are fixed

**Comment by liwangqian** [comment]
You mean the output message ? if so, you can disable this message by turn off the `debug` config.

**Comment by Nexela** [comment]
Not the message the luacheck warning not going away when fixed

**Comment by liwangqian** [comment]
But, from you snapshot, this warning is all right, which means this variable is not used.
If you don't like this warning, turn it down by adding 211(the warning code) to the `luacheck.ignore` config.

**Comment by Nexela** [comment]
There is no warning in the file.  The last warning is staying on the
problem list  even after it is fixed.  The only way to remove the problem
is to reload vscode. (Or close and reopen file if keep problems when closed
is fasle)

**Comment by liwangqian** [comment]
But, I cannot reproduce this problem:
![lint](https://user-images.githubusercontent.com/19996314/46616353-f26d4300-cb4c-11e8-869d-3613bdfef82b.gif)

**Comment by liwangqian** [comment]
I got it! This problem will be fix in next version.

**Comment by Nexela** [comment]
Thank you!   With all of the major issues out of the way I will be able to
recommend this mod for all things Lua

**Comment by Positive07** [comment]
I just wish this new release is pushed fast... it's quite annoying to face this issue

**Comment by liwangqian** [comment]
Will release tonight.

**Comment by liwangqian** [comment]
So this issue can be closed ? @Nexela

**Comment by Nexela** [comment]
Fixed. Thank you
