### ISSUE TITLE
Required symbols from externalPaths does not work when in workspace Scope

### ISSUE THREAD

**Issue by Nexela** [liwangqian/LuaCoderAssist#38]
I currently have this kind of setup

The main project `${workspaceFolder}/file.lua`

A library project `c:\develop\library\util.lua`

A symlink to my library project on LuaPath `c:\lua\modules\__library__`

How would I set it up so doing 
`Local Var = require('__library__/util')`
will correctly import the autocompletion and other features.

**Comment by liwangqian** [comment]
You mean the library path is not in the `workspaceFolder`? If is this scene, you can use the `externalPaths` configuration to specify the library path, for example:
```json
"LuaCoderAssist.search.externalPaths": [
    "c:\\develop\\library"
]
```
The extension will search the `externalPaths` for all lua files in it's subdirectories recursively.

**Comment by Nexela** [comment]
I can't seem to get this to work any way that I try it.  I think part of the problem is coming from the fact that I am using a path alias __library__ that is parsed by a custom require function in game and the actual folder is at c:\develop\library

**Comment by liwangqian** [comment]
@Nexela I try to make a folder hard link using the following cmd:
```cmd
F:\lua>mklink /H /J Penlight F:\Penlight\lua
```
and then:
```lua
local app = require('pl/app')
app.appfile()  -- this works well
```

![demo](https://user-images.githubusercontent.com/19996314/46569994-25b6a300-c990-11e8-852b-7a6f806d79fe.gif)

**Comment by liwangqian** [comment]
By the way, after adding a new symbol link to the workspace Root dir, reload vscode is needed.
And, the configuration `search.followLinks` must be `true`

**Comment by Nexela** [comment]
Followlinks and followsymlinks are true
And a reload was performed between attempts and it is not working

I will try to get more info In a few hours

**Comment by Nexela** [comment]
Ok I have narrowed this down to using workspaces.  Opening up the folder as an individual project works (mostly, see other issues)

[Info  - 6:32:39 PM] coder inited
[Info  - 6:32:39 PM] extension initialize status: true
[Info  - 6:32:39 PM] search c:\lua\luarocks\systree\share\lua\5.2 begin.
[Info  - 6:32:39 PM] search c:\lua\luarocks\lua begin.
[Info  - 6:32:39 PM] search e:\Develop\lua\factorio_mods\PickerMods\PickerPipeTools begin.
[Info  - 6:32:40 PM] search c:\lua\luarocks\systree\share\lua\5.2 end.
[Info  - 6:32:40 PM] search e:\Develop\lua\factorio_mods\PickerMods\PickerPipeTools end.
[Info  - 6:32:41 PM] search c:\lua\luarocks\lua end.

If this is loaded as a workspace the output is mostly the same however the begin and end for
[Info  - 6:32:39 PM] search e:\Develop\lua\factorio_mods\PickerMods\PickerPipeTools begin.
only lists the first project in the workspace and not the current project

**Comment by liwangqian** [comment]
Em, this extension is not adapt to the vscode's workspace feature, maybe this is the problem.

**Comment by liwangqian** [comment]
@Nexela The version 2.2.5 has support the wprkspace feature, will you have a try?

**Comment by Nexela** [comment]
I have been playing with 872a042a939159ae5ee27b13b79e0450338fab37  and it seemed to be working with it,  (as well as the outline working).   I will give the 2.2.5 release a try in a few hours and close this if all is still well.   Thank you for your work on this awesome extension.

**Comment by Nexela** [comment]
Seems to be working great! Thanks again for this and all other improvements you have been doing.
