### ISSUE TITLE
Hyphens in file names don't load symbols

### ISSUE THREAD

**Issue by Nexela** [liwangqian/LuaCoderAssist#39]
Hyphens in file name don't load symbols
local gui = require('mod-gui')  --doesn't load symbols for mod-gui.lua
local gui = require('modgui) -- loads symbols

Related #38

**Comment by Nexela** [comment]
To expand,   These are outside of workspace folder files in "LuaCoderAssist.search.externalPaths":

**Comment by liwangqian** [comment]
Well, I use the `/\w+/` to match the module name, so `'mod-gui'` will be `'gui'`, this is the problem.
By the way, module name like `'mod-gui'` is a good style ? ;)

**Comment by liwangqian** [comment]
Well, we use `/\w+$/` to match the module name, so `'mod-gui'` will be matched to `'gui'`, this is the problem.
By the way, is module name like `'mod-gui'` a common style?

**Comment by Nexela** [comment]
I can't attest to it being a common style but I do see `-` and `_` being used quite a bit in file names.
