### ISSUE TITLE
考虑支持new创建的对象的智能补全和静态检查

### ISSUE THREAD

**Issue by liwangqian** [liwangqian/LuaCoderAssist#4]
支持面向对象的编程风格，类似代码如下：
```lua

--- Object.lua
local Object = {}
function Object.new()
    return setmetatable({}, Object)
end

function Object:tostring()
    return "Object"
end

return Object
-------

------ some.lua
local Object = require('Object')

local newObj = Object.new()

print(newObj:tostring())

```

**Comment by Positive07** [comment]
This is handled pretty well in [autocomplete-lua](https://github.com/dapetcu21/atom-autocomplete-lua), and works for 70% of the cases (it fails sometimes).

The code for the metatable handling code is done [here](https://github.com/dapetcu21/atom-autocomplete-lua/blob/master/lib/extraction.js#L16L31) and [here](https://github.com/dapetcu21/atom-autocomplete-lua/blob/master/lib/extraction.js#L81L87) which are then used in the static [analysis part](https://github.com/dapetcu21/atom-autocomplete-lua/blob/aed302def3896cf945e1661e333fe8898ce5261e/lib/analysis.js#L158)

So maybe we could steal from them haha
