### ISSUE TITLE
Global vars that are returned don't load symbols

### ISSUE THREAD

**Issue by Nexela** [liwangqian/LuaCoderAssist#40]
Global tables that are returned don't load symbols (however the var itself correctly shows as a table)

fileA.lua
```lua
some_var = {}
function some_var.value() return true end
return some_var
```

fileB.lua
```
local some_thing = require('fileA')
-- both some_thing and some_var show up as table types however there are no symbols for them
```
![image](https://user-images.githubusercontent.com/13972192/46576366-be9bed00-c995-11e8-90fe-8e41fcc53520.png)

**Comment by liwangqian** [comment]
fix by https://github.com/liwangqian/LuaCoderAssist/commit/245ec3da85adde3418365088476734567db4b403

**Comment by Nexela** [comment]
Thanks for the fix.
