### ISSUE TITLE
No auto completion for files with more than one parent folder

### ISSUE THREAD

**Issue by grilledham** [liwangqian/LuaCoderAssist#41]
folder1/foo1.lua
```lua
local Foo1 = {}

function Foo1.foo()
    return true
end

return Foo1
```
folder1/folder2/foo2/lua
```lua
local Foo2 = {}

function Foo2.foo()
    return true
end

return Foo2
```
main.lua
```lua
local Foo1 = require('folder1.foo1')

local Foo2 = require('folder1.folder2.foo2')

Foo1.foo()

Foo2.foo()
```
![image](https://user-images.githubusercontent.com/10003572/46581137-bf329300-ca2a-11e8-82c0-99254d0d7c7c.png)

![image](https://user-images.githubusercontent.com/10003572/46581138-c8bbfb00-ca2a-11e8-840e-6331311ebdb1.png)

**Comment by liwangqian** [comment]
@grilledham Thanks for your feedback.

**Comment by grilledham** [comment]
Thank you. The latest release fixes this for me.
