### ISSUE TITLE
Lose type hinting for love when using require("love")

### ISSUE THREAD

**Issue by MikuAuahDark** [liwangqian/LuaCoderAssist#45]
It seems LCA doesn't specialize `require("love")` even if "Use LOVE libraries" is checked. This is bit troublesome for me because I always use `local love = require("love")` anywhere in my code. I wonder if it's possible to specialize `require("love")` in this case?

**Comment by MikuAuahDark** [comment]
Not to mention that the problem contradicts with Luacheck default setting. If I don't use `local love = require("love")`, Luacheck complains, but if I use that, I lose type hinting.

**Comment by liwangqian** [comment]
Well, this is a bug and will be fixed in next release version, thanks for you issue.
