### ISSUE TITLE
Functions declaration

### ISSUE THREAD

**Issue by labraxoid** [liwangqian/LuaCoderAssist#49]
**BUG in v.2.2.5 (  macOS 10.13.6 )**

I am currently creating [Corona](https://docs.coronalabs.com/) completions to add it to LuaCoderAssist like added Love compilations and discovered strange symbols behavior when declaring and defining functions.

In the first case problem with adding new fields to returned table (CASE 1):

![bug002](https://user-images.githubusercontent.com/17118730/50041372-e4fc9980-0064-11e9-9187-5d220b976035.gif)

In the second case problem is inclusion all fields in one object, but in Lua it is not true (CASE 2):

![bug003](https://user-images.githubusercontent.com/17118730/50041378-f6de3c80-0064-11e9-8929-8ef864f95de9.gif)

Alternative definition of the function (CASE 3):

![bug004](https://user-images.githubusercontent.com/17118730/50041382-06f61c00-0065-11e9-9930-bf9b828ea668.gif)

And once I caught this bug:

![bug005](https://user-images.githubusercontent.com/17118730/50041385-1bd2af80-0065-11e9-9ea1-e34c5886c55b.png)

Thanks for LuaCoderAssist! 
I hope my report will help make it better.

**Comment by liwangqian** [comment]
well, your issue is really detailed, thanks again, I will try to fix it later.

**Comment by labraxoid** [comment]
@liwangqian CASE 1 and CASE 2 are resolved but CASE 3 partially:

![bug007](https://user-images.githubusercontent.com/17118730/50818597-8ad7b700-1338-11e9-8a40-3ae0173999ce.gif)

Thank you for your efforts.

**Comment by labraxoid** [comment]
about CASE 2
now all fields and methods for simple tables are defined specifically, but for namedTypes from completions it works wrong, this is important because, as I noted above, I make the Corona completions, for Corona community. I attached edited love.json. You can replace original with it and check next situation:

![bug009](https://user-images.githubusercontent.com/17118730/50832297-d56c2a00-135e-11e9-8be7-9831e1c67d0a.gif)

[love.json.zip](https://github.com/liwangqian/LuaCoderAssist/files/2736834/love.json.zip)

**Comment by liwangqian** [comment]
@labraxoid For the Case 3 you describe up, we use the first definition of a symbol and will not change it's definition even thought we redefined it after some codes, so this case will not be resolved.

And, for the second case, the API description file `xxx.json`, should add `"kind": "constructor"` to the function to help figuring out that, it's a constructor, and we will create a new instance instead.

For example:
![image](https://user-images.githubusercontent.com/19996314/51075113-4ba3c000-16c2-11e9-8fdd-b46507e5dad1.png)

**Comment by labraxoid** [comment]
in CASE 3 is not about redefining, it is about different ways of function definition in Lua. The variable 'foo' is nil, we do not define it, we only declare. If we use way `function foo() ... end` LCA defines that variable 'foo' is function and we can see in outline all variables inside function but if we use `foo = function() ... end` LCA defines that variable 'foo' is function, defines type of function return but without definition variables inside. This is not a common situation, so if the implementation is difficult, then it can be omitted.

Thank you for extension of API completions. I will try it in next version.

**Comment by liwangqian** [comment]
@labraxoid Try the Ver2.2.8, CASE 3 is fixed in this version.
