### ISSUE TITLE
Setting the lineWidth does not work

### ISSUE THREAD

**Issue by Nelvin** [liwangqian/LuaCoderAssist#5]
I do have Lua files with longer lines but whatever I try to set lineWidth to - I always get the warning as well as the visual green line in the code. Would be great if one could disable this feature (or, of course, if the allowed lineWidth could be configured)

**Comment by liwangqian** [comment]
I think there is some misunderstanding of the lineWidth config, In current implemention, `LuaCoderAssist.format.lineWidth` is only affect the formatter, If you want to disable this diagnostic information, add the following config to you vscode's settings:
```json
"LuaCoderAssist.luacheck.ignore": [
        "631"
    ]
```
Refer http://luacheck.readthedocs.io/en/stable/warnings.html for more detail information.
Enjoy !

**Comment by Nelvin** [comment]
Ah yeah, now this works as I thought it's meant to be.

Also, I actually tried this setting but as in the VSC settings there's a comment for the ignore list
// Filter out warnings matching patterns.(@ref http://luacheck.readthedocs.io/en/stable/cli.html)
so I tried the strings meant to be used as CLI parameters but of course they did not work :)

Now I'll be able to give your plugin a real try - seems it's one of the best Lua plugins for VSC.

Thanks a lot for your fast reply & help
