### ISSUE TITLE
Return from return

### ISSUE THREAD

**Issue by labraxoid** [liwangqian/LuaCoderAssist#50]
**BUG in v.2.2.5 (  macOS 10.13.6 )**

When function returns values from return another functions the type of value are defining for first value only:

![bug006](https://user-images.githubusercontent.com/17118730/50102317-d1545d00-0235-11e9-87f4-d05ddf7e6941.gif)

Thanks for LuaCoderAssist! 
I hope my report will help make it better.

**Comment by liwangqian** [comment]
This is a bit hard to deal, since Lua is a dynamic language, and we can only provide LIMITTED type deduce.

**Comment by liwangqian** [comment]
@labraxoid Well, I just try to make it work, I'am not sure it works for all scenes, try the newest version and make some feedbacks, thank you!

**Comment by labraxoid** [comment]
@liwangqian Sorry for not responding before, I was on vacation. 
I confirm the issue is resolved. Thank you for your efforts.
