### ISSUE TITLE
Hang when opening certain files

### ISSUE THREAD

**Issue by MikuAuahDark** [liwangqian/LuaCoderAssist#52]
One example problematic file is this: https://github.com/MikuAuahDark/livesim2/blob/master/game/md5.lua

That file make sure correct MD5 is returned for certain input size due to bug in LOVE 11.2 and earlier, and use fallback in that case or if LOVE version is lower than 11.0.

Somehow, that file causes LuaCoderAssistant to hang. Once I open that file, then no type hinting, no keyword suggestion, no Luacheck, everything just stops as if I open a normal text file which affects all Lua files I open. One thing I notice is that when that happends, one of VS Code process fully uses one of my CPU core. When I terminate it, LuaCoderAssistant will complain that the server is closed, then everything backs to normal. However, once I open the problematic file again, the problem continues.

Enabling debug doesn't really help, there's no meaningful information I can get from the log (no, there's no message printed at all regarding that problem).

Version 2.2.6

EDIT: Seems not happen in version 2.2.5. Until this problem is fixed, I'll stay at 2.2.5 atm.

**Comment by liwangqian** [comment]
@MikuAuahDark Hi, this bug has been fixed, and will release in ver2.2.7

**Comment by labraxoid** [comment]
Hi,
I discovered the same behavior in the following situation:

![bug008](https://user-images.githubusercontent.com/17118730/50826580-16f3d980-134d-11e9-9f7d-7ea5c1f3c003.gif)

@liwangqian it is related with current issue or need to create new?

**Comment by liwangqian** [comment]
Em, This will be fixed in ver2.2.7
