### ISSUE TITLE
Server initialization failed Code: -32603

### ISSUE THREAD

**Issue by PaterFrog** [liwangqian/LuaCoderAssist#53]
For versions 2.2.6, 2.2.5 I get the following error: 

[Error - 4:35:40 AM] Server initialization failed.
  Message: Request initialize failed with message: Cannot read property 'map' of null
  Code: -32603 

Always the same error.
Version 2.2.3 is fine, no error. Others on Discord do not have the same error.

**Comment by liwangqian** [comment]
@PaterFrog 
Well, thanks for your issue, could you try to modify the file: `${__PATH__}\.vscode\extensions\liwangqian.luacoderassist-2.2.6\server\server.js`, line: 16, like the following code:
```js
var ok = coder.init({
    workspaceFolders: params.workspaceFolders || [],   //// modify this
line
    workspaceRoot: params.rootPath,
    connection: connection,
    documents: documents
});
```
and then, reload the plugin to check whether this problem is fixed.
