### ISSUE TITLE
Error: selectionRange

### ISSUE THREAD

**Issue by labraxoid** [liwangqian/LuaCoderAssist#55]
**ERROR in v.2.2.7 ( macOS 10.13.6 )**

![error 2019-01-11 9 52 57](https://user-images.githubusercontent.com/17118730/51018283-18f5ac80-1588-11e9-87cb-2c58821c91fe.png)

![bug010](https://user-images.githubusercontent.com/17118730/51018451-af29d280-1588-11e9-9b68-1aa83469d6f6.gif)

@liwangqian please, review closed issue #49 
Thanks!

**Comment by labraxoid** [comment]
[clans.lua.zip](https://github.com/liwangqian/LuaCoderAssist/files/2754424/clans.lua.zip)

**Comment by liwangqian** [comment]
@labraxoid Try ver2.2.8
