### ISSUE TITLE
require and init.lua for AwesomeWM

### ISSUE THREAD

**Issue by PapyElGringo** [liwangqian/LuaCoderAssist#57]
Hello and thanks for this extension that is really helpful!

Im working on the AwesomeWM and we are using extensively the use of the init.lua in folder to organize our code.

for example `/button/init.lua` instead of `/button/button.lua` to be able to do `local button = require('button')` instead of `local button = require('button.button)'`

To get **LuaCoderAssist** find my file for the moment I am forced to do `require('button.init')` is there a way to configure it to do so?

Thanks in advance

**Comment by liwangqian** [comment]
Currently，it's not possible to support this，I think it's not too hard to implement it.

**Comment by liwangqian** [comment]
This feature is publish in ver 2.2.9, close the issue.

**Comment by PapyElGringo** [comment]
Thanks you very much ! It's will help us a lot !

Le mar. 19 févr. 2019 à 12:10, liwangqian <notifications@github.com> a
écrit :
