### ISSUE TITLE
Autocomplete only names of functions, not parentheses and arguments

### ISSUE THREAD

**Issue by Aleshkev** [liwangqian/LuaCoderAssist#58]
I almost never call functions with all the arguments filled in. It would be extremely more convenient if pressing Tab (with a selected suggestion) inserted just the function name.

Example: if I write `love.graphics.setCanv` and press Tab, I would like it to just complete to `love.graphics.setCanvas`, *not* `love.graphics.setCanvas(canvas1, canvas2)`.

It can of course be just a configuration option.

**Comment by liwangqian** [comment]
@Aleshkev  Hi, in the newest version, you can enter 'delete' key to drop the auto complete parentheses and aruments.

**Comment by Aleshkev** [comment]
@liwangqian Thanks, but I don't think that's the best solution – that way people who like full auto-complete have to press Tab before being able to fill in the arguments, and people who don't like it (including me) have to press Del or Backspace.

IMO the best solution would be to add a configuration option e.g. `LuaCoderAssist.autoArgs`. If it is `false`, don't treat it as a snippet with values to be filled in, but just expand variable name.

I really think VS Code with this extension could be the best choice for LÖVE development right now, if only this change was made.

**Comment by liwangqian** [comment]
@Aleshkev As you suggested, a configuration `LuaCoderAssist.completion.autoInsertParameters` has been added in VER 2.3.0, try and make a feedback, thanks.
