### ISSUE TITLE
定义跳转在一些情况下不工作

### ISSUE THREAD

**Issue by ltccss** [liwangqian/LuaCoderAssist#6]
[main.txt](https://github.com/liwangqian/LuaCoderAssist/files/1567288/main.txt)
[myClass.txt](https://github.com/liwangqian/LuaCoderAssist/files/1567289/myClass.txt)
main中Test()无法跳转，New()可以

**Comment by liwangqian** [comment]
是的，跟issue #4是一样的，当前还没有实现获得函数的返回值类型，还没想好怎么实现。

**Comment by ltccss** [comment]
噗，原来是这样，那加油→。→
