### ISSUE TITLE
开发中会经常涉及getInstance方法，而往往提示不到对应的lua类

### ISSUE THREAD

**Issue by JiuMengDz** [liwangqian/LuaCoderAssist#60]
个人觉得对于getInstance方法可以提供一个检查接口关闭和自定义方法名的功能，可以大大方便检索和跳转

**Comment by liwangqian** [comment]
举个应用的例子呢？我这边没有这种应用场景，所以没有考虑到。

**Comment by JiuMengDz** [comment]
就是类似于实现了getInstance方法返回对应的对象表
比如我有一个表为UIController  里面有一个对应的getInstance方法返回这个对象，保证所有调用getInstance方法获得的对象都是同一个
所以在实际使用时是通过UIController.getInstance():showUI()这样的方式调用的，而实际上showUI就是UIController这个表中的一个函数，而现在的LuaCoderAssist并不能识别到showUI这个方法，因为中间有getInstance将这个方法所对应的表给分隔开了




------------------ 原始邮件 ------------------
发件人: "liwangqian"<notifications@github.com>;
发送时间: 2019年4月16日(星期二) 晚上11:37
收件人: "liwangqian/LuaCoderAssist"<LuaCoderAssist@noreply.github.com>;
抄送: "九梦岛主"<a326703305@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [liwangqian/LuaCoderAssist] 开发中会经常涉及getInstance方法，而往往提示不到对应的lua类 (#60)




举个应用的例子呢？我这边没有这种应用场景，所以没有考虑到。

**Comment by liwangqian** [comment]
如果在getInstance()里面能够简单推导出返回值类型，那应该是可以做补全的：
![image](https://user-images.githubusercontent.com/19996314/56671871-faa35f00-66e7-11e9-89b7-691a5ccf5199.png)
