### ISSUE TITLE
API接口描述文档的使用方式

### ISSUE THREAD

**Issue by JiuMengDz** [liwangqian/LuaCoderAssist#64]
在插件介绍中并未看到这个功能的使用教程或参考例子，请问这个部分是有什么效果，并且怎么使用的呢。
公司使用的是通过lua写Unity的代码，很多常用的UI控件函数调用往往很需要这样的辅助输入，如果可以自定义部分提示内容自然是再好不过了！

再次感谢你开发的这个插件，在内网编码特别需要这样的离线插件！

**Comment by liwangqian** [comment]
可以参考这个文件的写法：
https://github.com/liwangqian/LuaCoderAssist/blob/master/stdlibs/love.json

然后将文件保存成`.luacompleterc`，保存到workspace根目录下，重启应该就可以用了

**Comment by liwangqian** [comment]
你可以参考https://github.com/liwangqian/LuaCoderAssist/issues/22里面讨论的LOVE库API的自动生成方法
