### ISSUE TITLE
如何关闭函数上面的‘代码度量’

### ISSUE THREAD

**Issue by zouanfu** [liwangqian/LuaCoderAssist#65]
如标题，怎么才能关闭函数上面的代码度量，不想使用这个功能，感觉没什么用（如何用？）。

**Comment by Nexela** [comment]
"LuaCoderAssist.metric.enable": false,

![image](https://user-images.githubusercontent.com/13972192/59071471-c85f5280-888c-11e9-8882-4500be365d64.png)
