### ISSUE TITLE
The LuaCoderAssist server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by lx1986tao16** [liwangqian/LuaCoderAssist#66]
[Info  - 6:04:50 PM] coder inited
[Info  - 6:04:50 PM] extension initialize status: true
[Info  - 6:04:50 PM] Connection to server got closed. Server will restart.
[Info  - 6:04:51 PM] coder inited
[Info  - 6:04:51 PM] extension initialize status: true
[Info  - 6:04:51 PM] Connection to server got closed. Server will restart.
[Info  - 6:04:52 PM] coder inited
[Info  - 6:04:52 PM] extension initialize status: true
[Info  - 6:04:52 PM] Connection to server got closed. Server will restart.
[Info  - 6:04:53 PM] coder inited
[Info  - 6:04:53 PM] extension initialize status: true
[Info  - 6:04:53 PM] Connection to server got closed. Server will restart.
[Info  - 6:04:54 PM] coder inited
[Info  - 6:04:54 PM] extension initialize status: true
[Error - 6:04:54 PM] Connection to server got closed. Server will not be restarted.

**Comment by liwangqian** [comment]
well, could you please provide your plugin version and the plugin's config, maybe this is the same reason as issue #63 #59

**Comment by lx1986tao16** [comment]
[Info  - 11:33:47 AM] coder inited
[Info  - 11:33:47 AM] extension initialize status: true
[Info  - 11:33:47 AM] loading STD library ...
[Info  - 11:33:47 AM] search /Volumes/workSpace/Local/lobby/services/lobby begin.
[Info  - 11:33:48 AM] Connection to server got closed. Server will restart.

**Comment by lx1986tao16** [comment]
"name": "luacoderassist",
	"displayName": "LuaCoderAssist",
	"description": "lua编程助手，包括代码补全、符号预览&跳转、函数特征帮助、符号类型推导、静态检查、格式化、代码度量等功能",
	"icon": "images/icon.png",
	"version": "2.2.13",
	"publisher": "liwangqian",
	"engines": {
		"vscode": "^1.25.0"
	},

**Comment by lx1986tao16** [comment]
Own configuration :
"LuaCoderAssist.luacheck.execPath": "/usr/local/bin/luacheck",
"LuaCoderAssist.format.quotemark": "double",

**Comment by lx1986tao16** [comment]
Error reported after LuaCheck configuration is turned on

**Comment by lx1986tao16** [comment]
已经找到问题了，谢谢

**Comment by datavisorchengpeng** [comment]
@lx1986tao16 请问是怎么解决的呢
