### ISSUE TITLE
Question: How to properly set "LuaCoderAssist.search.externalPaths"

### ISSUE THREAD

**Issue by rucciva** [liwangqian/LuaCoderAssist#7]
i have a file in my project directory (**./volumes/kong/lua/5.1/kong/plugins/basic-auth/handler.lua**) which require another sibling file (**./volumes/kong/lua/5.1/kong/plugins/basic-auth/access.lua**).

the require was defined like this :
-- in handler.lua
`local access = require "kong.plugins.basic-auth.access"`

i would like to have code completion from the **access** variables.

My question are

1. does your plugins support this kind of code-completion scenario?
2. if so, does **LuaCoderAssist.search.externalPaths** config related to this scenario?
3. if it is, how do i properly set **LuaCoderAssist.search.externalPaths**?

thanks

**Comment by liwangqian** [comment]
@rucciva Sorry for late reply, this scenario is supported, as it is showed in the demo of `signature help`(see README.md), have a try and any issues is welcomed.

**Comment by rucciva** [comment]
thanks for the reply.

If it is supported, then please guide me to set up my project.

<img width="1280" alt="screen shot 2018-01-02 at 08 48 25" src="https://user-images.githubusercontent.com/4647473/34472691-d019f1fc-ef99-11e7-9512-d602d5872ca6.png">

as you can see from the image above, i can't seem to get suggestion regarding functions available under "access" variables 

my current _workspace setting_ is this
```
{
    "LuaCoderAssist.luacheck.execPath": "/Users/rucciva/.luarocks/bin/luacheck",
    "LuaCoderAssist.search.externalPaths": [
        "/Users/rucciva/Temporary/kong-plugin/volumes/kong/usr/local/share/lua/5.1/"
    ]
}
```

my workspace root directory is _/Users/rucciva/Temporary/kong-plugin/_
and both of the files are under _/Users/rucciva/Temporary/kong-plugin/volumes/kong/usr/local/share/lua/5.1/kong/plugins/basic-auth_

thanks

**Comment by liwangqian** [comment]
@rucciva I got the problem, and it's fixed in the newlest version 1.3.1, try again please.
![image](https://user-images.githubusercontent.com/19996314/34615695-c5cbc6a6-f270-11e7-9c63-6ea2d93e5c08.png)

**Comment by rucciva** [comment]
cool, it works now, thank you very much

but i found another issues. It doesn't seem to be able do display suggestions from a local table that is defined and returned in a function. Another question arises too, does your plugin follows __index metamethods?

for example in this code:
<img width="1280" alt="screen shot 2018-01-06 at 09 29 21" src="https://user-images.githubusercontent.com/4647473/34635567-21889ed0-f2c4-11e7-8262-c0df371ca2a3.png">

As we can se, **Object:extend()** return **cls** which has **self** fields and it's **__index** points to Object. But when invoking Object:extend(), **self** and Object's method such as **extend**(), **implement**(), etc are not displayed in the suggestion

nb: i am using https://github.com/Kong/kong as an example, the two files displayed are: _kong/plugins/base_plugin_ and _kong/vendor/classic_

**Comment by liwangqian** [comment]
@rucciva Currently, value return from a general function cannot be parsed, so suggestion is unavailable, a new symbol engine is under developing, but slowly, I'm too busy in work, So welcome contribute MR. ：）

**Comment by rucciva** [comment]
i see, that's fine. i'll try to contribute if i can.
thanks anyway. i think i'll close this issue
