### ISSUE TITLE
Feature Request: hide self refrence on auto complete when using : notation

### ISSUE THREAD

**Issue by Nexela** [liwangqian/LuaCoderAssist#70]
Is it possible to detect when an auto complete contains a preceding `:` and remove the first parameter from the list

```lua
local tab = {}
function tab.some_func(a, b)
end
```

`tab:some_fun` will auto complete to `tab:some_func(b)`

**Comment by liwangqian** [comment]
it is possible @Nexela 
Try in the version 2.3.2

**Comment by Nexela** [comment]
Works great! Thank you.
