### ISSUE TITLE
typing the period or colon in `function tableName.() end` produces an error if tableName is not defined

### ISSUE THREAD

**Issue by tesselode** [liwangqian/LuaCoderAssist#81]
![ezgif com-optimize](https://user-images.githubusercontent.com/2637802/71780288-b5317400-2f8e-11ea-97a6-1e768818ce28.gif)

Steps to reproduce:

1. Type the following code (the function name can be anything):

```lua
function test()
end
```

2. Add a period or colon after the function name so the code looks like this:

```lua
function test.()
end
```

or:

```lua
function test:()
end
```

3. The output pane immediately opens, showing an error like this:

```
[Error - 7:41:51 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'type' of undefined
  Code: -32603 
```

This only happens if the name before the period or colon is not an existing variable. For example, this does not produce an error:

```lua
local test = {}

function test.()
end
```

**Comment by liwangqian** [comment]
@tesselode Thanks your feedback

**Comment by tesselode** [comment]
thanks for the fix!
