### ISSUE TITLE
Cannot read property 'description' of null

### ISSUE THREAD

**Issue by Nexela** [liwangqian/LuaCoderAssist#90]
[Error - 12:21:15 AM] Request completionItem/resolve failed.
  Message: Request completionItem/resolve failed with message: Cannot read property 'description' of null
  Code: -32603 

Easiest way I have found to reproduce is to install the `lua local debugger` extension and type
`lldebuger.`

**Comment by liwangqian** [comment]
This does not reproduce in my environment, I make some check in code, maybe you can try whether it fix.

**Comment by Nexela** [comment]
I am not sure why, but I can't even get this to reproduce.
