### ISSUE TITLE
中文函数变量点击不能自动跳转

### ISSUE THREAD

**Issue by luhongweiyu** [liwangqian/LuaCoderAssist#91]
中文函数变量点击不能自动跳转,另外可不可以增加个自定义函数特征提示的扩展,谢谢大大

**Comment by liwangqian** [comment]
还可以用中文作为函数名吗？这个有点另类啊。

**Comment by liwangqian** [comment]
另外可不可以增加个自定义函数特征提示的扩展
-- 这个你只的是通过增加注解的方式吗？
