### ISSUE TITLE
Prevent auto-formating

### ISSUE THREAD

**Issue by vitorbertolucci** [liwangqian/LuaCoderAssist#92]
I looked through the settings and did not find any to disable auto formatting. I like many of the extension's features but would like to disable auto-formating upon save, because it changes all my quotes either to simple or double quotes and in our organization we have use for both of them.

**Comment by liwangqian** [comment]
`Format On Save`  is an editor feature, search the `format` key word in your settings.

**Comment by vitorbertolucci** [comment]
Oh, sorry about that. My bad. Thank you.

And what about an extension setting for only disabling the quote formatting? So we don't need to choose between only using single or double quotes.
