### ISSUE TITLE
macos 安装插件后，立即报错

### ISSUE THREAD

**Issue by TQING1990** [liwangqian/LuaCoderAssist#95]
macos   版本: 10.14.6
vscode  版本: 1.43.1
插件版本: 2.3.9 (其他版本也试过，一样的错误，可能和 vscode 更新有关？)

错误信息：
[Info  - 11:06:14 AM] coder inited
[Info  - 11:06:14 AM] extension initialize status: true
[Info  - 11:06:19 AM] Connection to server got closed. Server will restart.
[Info  - 11:06:20 AM] coder inited
[Info  - 11:06:20 AM] extension initialize status: true
[Info  - 11:06:20 AM] Connection to server got closed. Server will restart.
[Info  - 11:06:20 AM] coder inited
[Info  - 11:06:20 AM] extension initialize status: true
[Info  - 11:06:21 AM] Connection to server got closed. Server will restart.
[Info  - 11:06:21 AM] coder inited
[Info  - 11:06:21 AM] extension initialize status: true
[Info  - 11:06:22 AM] Connection to server got closed. Server will restart.
[Info  - 11:06:22 AM] coder inited
[Info  - 11:06:22 AM] extension initialize status: true
[Error - 11:06:22 AM] Connection to server got closed. Server will not be restarted.

**Comment by TQING1990** [comment]
与 #86 的情况很像

**Comment by TQING1990** [comment]
把 luacheck 关闭掉就正常了

**Comment by liwangqian** [comment]
自带的luacheck是exe可执行文件，不适用于MacOS

**Comment by hwgy2008** [comment]
Mac上通过luarocks安装luacheck（参考https://github.com/mpeterv/luacheck），然后在设置“Path of the luacheck excutable”的时候填入luacheck就可以了
